name=ESP_NOW_DEVICE
version=1.0.0
author=Avramenko Pavlo
maintainer=Avramenko Pavlo
sentence=ESP-NOW communication library
paragraph=Library for ESP-NOW devices gatawey to MQTT and Telegram
category=Communication
architectures=esp8266

depends=ArduinoJson
depends=WakeOnLan
depends=PubSubClient
depends=FastBot2
depends=OneWire